id: I35053403
legacy_id: P004450
ocr_import_info:
  bdrc_scan_id: W2CZ5669
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T10:06:47'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T14:58:01.156728+00:00'
last_modified: 2022-09-02 22:58:50.271692
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ5669
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ5669
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འཇིགས་བྱེད་ལྷ་བཅུ་གསུམ་གྱི་བསྐྱེད་རྫོགས་ཁྲིད་ཡིག
  author: ཐུབ་བསྟན་ཡར་འཕེལ་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.5259659713915852
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I1KG10573:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG10573
      total_pages: 370
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG10573.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.5259659713915852
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
